Arun's Week 7 Drop Down Changes and Svg Additions
ucladevx/twain-extension pull request #6
Opened 2019-11-20 02:29 UTC by abhattasali

Modified Nav.js to Add Drop Down for settings and help pages; imported svg icons Help and Settings (modified); Settings.js development

2019-11-21 04:49 UTC, alexlongerbeam requested changes
Overall the code looks good! Can you address my comments and also add some screenshots/screen recordings to the Pull Request to basically show proof that things look as expected?

2019-11-21 04:49 UTC, alexlongerbeam commented on src/components/containers/Nav.js
> +  // }
Remove these before merging

2019-11-21 04:49 UTC, alexlongerbeam commented on src/components/containers/Nav.js
> +
Clean up all the extra lines here

2019-11-27 03:05 UTC, abhattasali commented
Made edits to original PR.

2019-11-27 04:37 UTC, alexlongerbeam approved these changes
Looks awesome!

2019-11-27 06:29 UTC, merged